### ISSUE TITLE
Design for landing page

### ISSUE THREAD

**Issue by GergoN02** [MMU-SE/Frontend#6]
Post it here once done so we can start working from it

**Comment by MA1002643** [comment]
![photo](https://user-images.githubusercontent.com/87866666/221288345-0dcdade2-07fd-4158-a231-40fda9bb1c00.png)

**Comment by MA1002643** [comment]
> ![photo](https://user-images.githubusercontent.com/87866666/221288345-0dcdade2-07fd-4158-a231-40fda9bb1c00.png)

This is a rough Idea of the Dashboard we can have. Please let me know anymore Ideas you have we can work off it to add more things in it.

**Comment by GergoN02** [comment]
Looks good, I'll start building something like this out tomorrow.
